# Generated by Django 5.2.3 on 2025-06-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('completionDateTime', models.DateTimeField()),
            ],
        ),
    ]
